resources/views/client/dashboard.twig
It should be `cursor-pointer` instead of `cursor.pointer`.
https://tailwindcss.com/docs/cursor/#pointer
=> Fix typo in pointer cursor class

app/Commands/ShareCurrentWorkingDirectoryCommand.php
Hello Marce. 
This PR FIxes #12 . it allows default command to pass subdomain and only override if missing
```
expose --subdomain=bar
```
=> Skip subdomain override if provided

config/expose.php, docs/client/configuration.md
The section header was a duplicate of a previous header
=> Fix duplicate config section header

app/Commands/ShareCurrentWorkingDirectoryCommand.php
Even though it's perfectly valid, some providers (Paddle in our case) don't validate URLs with an underscore in them as valid, an easy fix is just using a dash instead.
=> Don't use underscore in subdomain

app/Client/Client.php
Hi,
After some testing I noticed a little bug in the calculation of remaining time when using `maximum_connection_length` option on the server.
`DateTime::createFromFormat('s', $seconds)` [can only take seconds up to 99 (max 2 digits) seconds](https://web.tinkerwell.app/#/snippets/e64588b5-1ed8-4fc4-944a-f36652d8d20b). If remaining time is more, the following error appears:
(I didn't add any tests as I'm new to reactphp and simply don't know how to set this up, hope this fix help anyway 😅)
=> fix remaining time calculation

.gitattributes
Thanks for starting this cool project!
I noticed that the `.gitattributes` file `export-ignore` rules were a little out of date, hence this PR. Excluding the `builds/expose` file (which I believe should not be bundled, but that's for another discussion), this PR reduces the zip file download size from 132kb to 106kb with standard GitHub zip downloads. 
Thank you.
=> Update .gitattributes to export-ignore tests, docs, and other build files

app/Contracts/UserRepository.php, app/Server/Http/Controllers/Admin/GetUsersController.php, app/Server/Http/Controllers/Admin/ListUsersController.php, app/Server/UserRepository/DatabaseUserRepository.php, resources/views/server/users/index.twig
This PR implements a very basic pagination on the users page regarding issue #51 .
If it's got merged the upcoming PR I would try to make is to add search input so it's easy to filter users by name or token.
=> Add simple pagination to users page 

app/Commands/ShareCurrentWorkingDirectoryCommand.php
This PR fixes issue #60, It will try to compare the project path with any valet links in `$VALET/Sites` directory. if any matches we use the basename of the link. if not it will fallback to project path directory name
=> Auto detect valet links

app/Contracts/ConnectionManager.php, app/Server/Connections/ConnectionManager.php, app/Server/Connections/ControlConnection.php, app/Server/Factory.php, app/Server/Http/Controllers/Admin/GetUserDetailsController.php, app/Server/Http/Controllers/ControlMessageController.php, app/Server/UserRepository/DatabaseUserRepository.php, tests/Feature/Server/AdminTest.php, tests/Feature/Server/ApiTest.php
This PR allows the association between a shared site and the authentication token / user.
It also adds a new API endpoint `/api/users/{ID}` which shows you all shared sites for a given user.
The paginated user API also contains a new `site` attribute that holds all shared sites for the user.
=> Associate shared sites with auth tokens

Dockerfile
executing expose in the container
before:
```
docker run -it expose ./expose
```
after:
```
docker run -it expose expose
```
inspiration taken from [cangelis' docker](https://github.com/cangelis/expose-docker)
=> make expose directly executable in the docker container

app/Client/Http/HttpClient.php
As described in #146 the fixed IP address for DNS can cause problems if another DNS is configured in the system.
=> Removed fixed IP address for DNS

app/Providers/AppServiceProvider.php, docs/client/configuration.md
**What does this PR do?**
It adds the ability to provide a path for your config file.
**Why this PR?**
Here are some use cases:
[Server] When you want to use multiple domains to be served by one expose codebase but with different databases.
[Client] You want to use multiple host domains without changing your config file.
**How to use this functionality**
Add `EXPOSE_CONFIG_FILE="/absolute/path/to/config.php"` to your expose command with the absolute path to your config file.
=> Allow custom config file path

composer.json
This PR bumps an update to Cuzzle, which has a patch to fix escapeshellargs, allowing requests larger than 8k bytes to be processed.
=> Update Cuzzle to 3.1

app/Commands/ShareCurrentWorkingDirectoryCommand.php, config/expose.php
When running `expose` without any options it tries to detect some Valet configuration and defaults to `http://[FOLDER].[DEFAULT_TLD]`. On some systems HTTPS may be the standard for sites, so I added an option to define whether HTTPS should be used as an default.
=> feat: Config option to set default protocol to https

app/Client/Configuration.php, app/Client/Factory.php, app/Client/Fileserver/ConnectionHandler.php, app/Client/Fileserver/Fileserver.php, app/Client/Http/HttpClient.php, app/Client/ProxyManager.php, app/Commands/ShareFilesCommand.php, app/Http/Controllers/Concerns/LoadsViews.php, app/Server/Connections/ControlConnection.php, app/Server/Http/Controllers/TunnelMessageController.php, resources/views/client/fileserver.twig, tests/Feature/Client/DashboardTest.php, tests/Feature/Client/FileserverTest.php, tests/fixtures/test.md, tests/fixtures/test.txt
This PR adds a built-in fileserver to expose.
Possible commands are:
```
expose share-files
expose share-files ~/Documents
expose share-files ~/Documents --name="*.jpg"
```
As this starts an internal HTTP server, it can be combined with all existing expose options, like specifying the subdomain, or adding basic authentication.
=> Add built-in fileserver

Dockerfile, docker-entrypoint.sh
Hey,
You've created an amazing tool and I'm going to run on my own server (with Docker).
I see that a change on entrypoint in #149 causes a bug with CMD in Docker see in #165.
I purpose to create a custom endpoint to keep behavior for run default cmd and also a custom command if you want in your docker run.
I'm waiting your advise especially for entrypoint sh file that I've put on root but maybe you want to create a special folder for "Docker stuff".
=> Fix docker entrypoint

resources/views/server/errors/404.twig, resources/views/server/homepage.twig
Looking for docs of `expose` I found out that the link in home (and 404 page) redirects to the same website instead of the official beyondco.de documentation.
Is it intended?
If not, here a PR to fix it, otherwise sorry :)
This PR replaces:
```
Do you want to host your own Expose server? Check out the <a href="https://sharedwithexpose.com" class="underline">official documentation</a>.
```
With:
```
Do you want to host your own Expose server? Check out the <a href="https://beyondco.de/docs/expose" class="underline">official documentation</a>.
```
In the homepage and 404 error page.
=> Fix documentation link in home and 404 page

app/Server/Factory.php
If you set config `expose.admin.statistics.enable_statistics` to false, the server will not start because "registerStatisticsCollector()" will not return it self ("Call to a member function bindConnectionManager() on null").
=> Always return '$this' in 'registerStatisticsCollector'

docker-compose.yml
This PR adds host.docker.internal:host-gateway to extra_hosts section in docker-compose.yml
In docker for Mac and Windows hosts, we can connect to the host out of the box by using the special DNS name:host.docker.internal.
When docker is running under linux host, this is not the case. Under linux we need the magic string host-gateway to map to the gateway inside the container. This allows the hostname host.docker.internal to access the host from inside a container.
This fix is necessary for Linux users that use expose under docker and the webserver they want to expose is running as docker container too (ex. laravel sail).
The issue is explained in depth in this this article:
https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66
=> Docker container: access linux host

resources/views/client/dashboard.twig
This PR adds a nice JSON viewer to both the request and the response output in the Expose dashboard.
In addition to this, it also adds a button to quickly copy the request and response body
=> Add JSON viewer to dashboard

docs/getting-started/installation.md
The `wget` command downloads a `expose` file, not `expose.phar` file.
=> Fix installation.md

docs/getting-started/sharing-your-first-site.md
Https should be put before (prepend) the url, so prepend should be the correct word. Append would mean you put it after.
=> Typo: append should actually be prepend

docs/getting-started/installation.md
Before: https://expose.dev/docs/expose/getting-started/sharing-your-first-site
After: https://expose.dev/docs/getting-started/sharing-your-first-site
=> Fixed wrong url
